# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on:
  create:
    tags:
      - v*

name: Cross-compile

jobs:
  build:
    name: Build tool
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [x86_64, i686, arm, aarch64]
        include:
        - build: x86_64
          target: x86_64-unknown-linux-gnu
          strip: x86_64-linux-gnu-strip
        - build: i686
          target: i686-unknown-linux-gnu
          strip: i686-linux-gnu-strip
        - build: arm
          target: arm-unknown-linux-gnueabi
          strip: arm-linux-gnueabi-strip
        - build: aarch64
          target: aarch64-unknown-linux-gnu
          strip: aarch64-linux-gnu-strip
        tool:
          - bat
          - exa
          - fd
          - lsd
          - rg
          - sd
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - name: Cargo build
        uses: marcopolo/cargo@master
        with:
          command: build
          working-directory: tools/${{ matrix.tool }}
          use-cross: true
          args: --verbose --release --target ${{ matrix.target }}

      # - name: Compress binaries
      #   uses: svenstaro/upx-action@v2
      #   with:
      #     file: tools/${{ matrix.tool }}/target/${{ matrix.target }}/release/${{ matrix.tool }}
      #     strip: false
      - name: Strip binary
        if: matrix.build == 'x86_64' || matrix.build == 'i686'
        run: strip tools/${{ matrix.tool }}/target/${{ matrix.target }}/release/${{ matrix.tool }}
      - name: Strip release binary (docker)
        if: matrix.build == 'arm' || matrix.build == 'aarch64'
        run: |
          docker run --rm -v \
            "$PWD/tools/${{ matrix.tool }}/target:/target:Z" \
            rustembedded/cross:${{ matrix.target }} \
            ${{ matrix.strip }} \
            /target/${{ matrix.target }}/release/${{ matrix.tool }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tools/${{ matrix.tool }}/target/${{ matrix.target }}/release/${{ matrix.tool }}
          asset_name: ${{ matrix.tool }}-${{ matrix.target }}
          tag: ${{ github.ref }}
