# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on:
  create:
    tags:
      - v*

name: Cross-compile

jobs:
  build:
    name: Build tool
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - arm-unknown-linux-gnueabi
          - aarch64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
        tool:
          - fd
          - sd
          - ripgrep
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - name: Cargo build
        uses: marcopolo/cargo@master
        with:
          command: build
          working-directory: tools/${{ matrix.tool }}
          use-cross: true
          args: --verbose --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.tool }}-${{ matrix.target }}
          path: tools/${{ matrix.tool }}/target/release/*