# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on:
  create:
    tags:
      - v*

name: Cross-compile

jobs:
  build:
    name: Build fd
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # - arm-unknown-linux-gnueabi
          - aarch64-unknown-linux-gnu
          # - i686-unknown-linux-gnu
          # - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Use Cross
        run: cargo install cross
      - name: Build release Binary
        run: cross build --verbose --release --target ${{ matrix.target }} --manifest-path tools/fd/Cargo.toml --target-dir dist

      - uses: actions/upload-artifact@v2
        with:
          name: fd
          path: dist/release/fd