# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on:
  create:
    tags:
      - v*

name: Cross-compile

jobs:
  build:
    name: Build fd
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # - arm-unknown-linux-gnueabi
          - aarch64-unknown-linux-gnu
          # - i686-unknown-linux-gnu
          # - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --release --manifest-path tools/fd/Cargo.toml --target-dir dist